name: ICUpy
dependencies:
  - python=3.9
  - pip
  - ipython
  - pandas
  - pytest
  - pytest-cov
  - numpy
  - nbconvert
  - nbformat
  - jupyter
  - jupyterlab
  - pip:
    - black
    - pre-commit
    - joblib
    - matplotlib
    - scipy
    - scikit-learn
    - seaborn
    - pingouin
    - jupyter_contrib_nbextensions
    - autopep8
